name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Python
        run: python --version
      - name: Success
        run: echo "CI Passed"
